sudo: required
services:
  - docker

before_install:

script:
  echo "no tests"

after_success:
  - docker build -t rocky1638/mrr-fe ./frontend
  - docker build -t rocky1638/mrr-api ./api
  - docker build -t rocky1638/mrr-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push rocky1638/mrr-fe
  - docker push rocky1638/mrr-api
  - docker push rocky1638/mrr-nginx
