version: '3'
services:
  api:
    build:
      context: ./api
  fe:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
